### ISSUE TITLE
=media-gfx/niftyled-9999 fails to compile against babl

### ISSUE THREAD

**Issue by waebbl** [niftylight/niftyled#18]
After the babl update (commit e52d847240a22701320785a3260bd0fca36c64f0), niftyled no longer compiles against any stable or unstable babl. The user is forced to install babl-9999 to be able to successfully compile.

**Comment by niftylight** [comment]
yes. Since niftyled used the internal API from babl and they recently stripped all symbols, that was the most reasonable solution. The next babl release will fix this. Until then, manually install current babl master.
